# Generated by Django 3.2.5 on 2021-08-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
